[package]
name = "zite"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.10", features = ["derive"] }
comrak = "0.26"
tera = "1.20.0"
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.120"
toml = "0.8.17"
